# Joint configuration for joint_state_publisher_gui

joint_state_publisher:
  ros__parameters:
    # Joint names and default positions
    zeros:
      left_elb_fex_joint: 0.0
      left_fam_rot_joint: 0.0
      left_ind_dip_joint: 0.0
      left_ind_mip_joint: 0.0
      left_ind_pip_joint: 0.0
      left_mid_dip_joint: 0.0
      left_mid_mip_joint: 0.0
      left_mid_pip_joint: 0.0
      left_pnk_dip_joint: 0.0
      left_pnk_mip_joint: 0.0
      left_pnk_pip_joint: 0.0
      left_rng_dip_joint: 0.0
      left_rng_mip_joint: 0.0
      left_rng_pip_joint: 0.0
      left_shd_aad_joint: 0.0
      left_shd_fex_joint: 0.0
      left_shd_rot_joint: 0.0
      left_thb_ip_joint: 0.0
      left_thb_mip_joint: 0.0
      left_wrs_fex_joint: 0.0
      right_elb_fex_joint: 0.0
      right_fam_rot_joint: 0.0
      right_ind_dip_joint: 0.0
      right_ind_mip_joint: 0.0
      right_ind_pip_joint: 0.0
      right_mid_dip_joint: 0.0
      right_mid_mip_joint: 0.0
      right_mid_pip_joint: 0.0
      right_pnk_dip_joint: 0.0
      right_pnk_mip_joint: 0.0
      right_pnk_pip_joint: 0.0
      right_rng_dip_joint: 0.0
      right_rng_mip_joint: 0.0
      right_rng_pip_joint: 0.0
      right_shd_aad_joint: 0.0
      right_shd_fex_joint: 0.0
      right_shd_rot_joint: 0.0
      right_thb_ip_joint: 0.0
      right_thb_mip_joint: 0.0
      right_wrist_fex_joint: 0.0

    # Joints to publish
    source_list:
      - left_elb_fex_joint
      - left_fam_rot_joint
      - left_ind_dip_joint
      - left_ind_mip_joint
      - left_ind_pip_joint
      - left_mid_dip_joint
      - left_mid_mip_joint
      - left_mid_pip_joint
      - left_pnk_dip_joint
      - left_pnk_mip_joint
      - left_pnk_pip_joint
      - left_rng_dip_joint
      - left_rng_mip_joint
      - left_rng_pip_joint
      - left_shd_aad_joint
      - left_shd_fex_joint
      - left_shd_rot_joint
      - left_thb_ip_joint
      - left_thb_mip_joint
      - left_wrs_fex_joint
      - right_elb_fex_joint
      - right_fam_rot_joint
      - right_ind_dip_joint
      - right_ind_mip_joint
      - right_ind_pip_joint
      - right_mid_dip_joint
      - right_mid_mip_joint
      - right_mid_pip_joint
      - right_pnk_dip_joint
      - right_pnk_mip_joint
      - right_pnk_pip_joint
      - right_rng_dip_joint
      - right_rng_mip_joint
      - right_rng_pip_joint
      - right_shd_aad_joint
      - right_shd_fex_joint
      - right_shd_rot_joint
      - right_thb_ip_joint
      - right_thb_mip_joint
      - right_wrist_fex_joint